### PR TITLE
Use project name instead of generic name

### PR DESCRIPTION
**Pull request by kattjevfel**
As title implies, this changes all instances of the rather generic name "gpuStatsServer" to the project name "ksysguard-gpu". I am currently packaging this for arch and am renaming the files before packaging, but it'd obviously be nicer if it were done upstream.

### CODE REVIEW

**Comment by lestofante** [comment]
Thanks, merged and I also released a stable package (guess based on your), here: https://aur.archlinux.org/packages/ksysguard-gpu/

You should update your as right now is broken as of this merge.

I think that will be the last breaking change

**Comment by kattjevfel** [comment]
> You should update your as right now is broken as of this merge.

Way ahead of ya, done 2 hours before you posted ^^
https://aur.archlinux.org/cgit/aur.git/commit/?h=ksysguard-gpu-git&id=d504854d42bd5f180dc139ed0ad37e191df42cd9

Thanks for merging!

**Comment by lestofante** [comment]
found out we are missing the dependency from ksysguard xD

**Comment by kattjevfel** [comment]
If you mean the package should depend on ksysguard I did that on purpose. The script could be used to monitor a GPU in another system on which you don't want half of KDE on (like a server). Asides, namcap was complaining about it.

**Comment by lestofante** [comment]
make sense.
Actually i wanted to create a client to always log the GPU in background, so I could easily export the usage statistic during long gameplay

**Pull request merged**
